migrate frontend to typescript (#60)
gsproston-scottlogic/prompt-injection pull request #77
Opened 2023-07-27 15:58 UTC by scottrowan

moving to typescript:

major things,
- .js, .jsx files now .ts, .tsx
- tsconfig.json added to root dir
- we never pass "props" always a typed object with a defined interface
- interfaces defined and xported from the service files
- components changed to pass down typed objects rather than individual fields
- all function args and local variables / useStates etc have types defined

sorry the diff isn't so easy to read because its technically deleting / creating new files, not much I can do about that

all my type interfaces are named OpenAI*, such as OpenAIMessage, OpenAIResponse, OpenAIDefence etc, feel free to propose better names

2023-07-27 16:12 UTC, scottrowan commented
noticed this will almost certain clash with George's PR, sure merge that first then I'll make a few changes here

2023-07-28 09:36 UTC, gsproston-scottlogic requested changes
Looks good! I do agree that we should change any references to 'OpenAI' to something else. I reckon if it's related to the LLM, then change it to `chatBot...`, and just remove it from the email and defence interfaces.

2023-07-28 09:36 UTC, gsproston-scottlogic commented on frontend/src/components/ChatBox/ChatBox.tsx
> +    setEmails: (emails: any) => void;
Could we type emails here with `OpenAIEmail`?

2023-07-28 09:36 UTC, gsproston-scottlogic commented on frontend/src/components/DefenceBox/DefenceBox.tsx
> +    })
If we have `isActive` and `isTriggered` default to `false` in the interface definition, we don't need this `map` here.

2023-08-03 12:50 UTC, gsproston-scottlogic commented on frontend/src/service/defenceService.ts
> +  isTriggered?: boolean;
Ended up using a class with a constructor here as it doesn't look like it's possible to have default values in a TS interface.

2023-08-03 12:55 UTC, gsproston-scottlogic approved these changes

2023-08-03 15:11 UTC, heatherlogan-scottlogic approved these changes

2023-08-03 15:12 UTC, merged