57 user input api key
gsproston-scottlogic/prompt-injection pull request #88
Opened 2023-08-03 10:08 UTC by heatherlogan-scottlogic

2023-08-03 10:15 UTC, heatherlogan-scottlogic commented
Requires ts-frontend to be merged

2023-08-08 08:58 UTC, gsproston-scottlogic requested changes

2023-08-08 08:58 UTC, gsproston-scottlogic commented on frontend/src/components/ApiKeyBox/ApiKeyBox.tsx
> +      />
Would it be possible to hide the key in some way? I'm thinking like a password input. Just so the user doesn't have their API key on display all the time.

2023-08-08 08:58 UTC, gsproston-scottlogic commented on backend/src/openai.js
>  }
Could we have it so if the .env contains an OPENAI_API_KEY, then it uses that by default, and doesn't require the user to input a key. Would be easier for dev work.

2023-08-08 08:58 UTC, gsproston-scottlogic commented on frontend/src/service/openaiService.ts
This file got renamed to 'chatService.ts' so it looks like GitHub thinks this is a new file.

2023-08-08 13:58 UTC, gsproston-scottlogic approved these changes
Looks great!

2023-08-08 14:01 UTC, merged